
install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))

remotes::install_github("rjdverse/rjd3toolkit")
remotes::install_github("rjdverse/rjdemetra")
remotes::install_github("rjdverse/rjd3bench")
remotes::install_github("rjdverse/rjd3providers")
remotes::install_github("rjdverse/rjd3revisions")
remotes::install_github("rjdverse/rjd3nowcasting")
remotes::install_github("rjdverse/rjd3x13")
remotes::install_github("rjdverse/rjd3workspace")
remotes::install_github("rjdverse/rjd3tramoseats")
remotes::install_github("rjdverse/rjd3sts")
remotes::install_github("rjdverse/rjd3filters")
remotes::install_github("rjdverse/rjd3highfreq")
remotes::install_github("rjdverse/rjd3stl")
remotes::install_github("rjdverse/rjd3x11plus")

libary("rjd3toolkit")
libary("rjdemetra")
libary("rjd3bench")
libary("rjd3providers")
libary("rjd3revisions")
libary("rjd3nowcasting")
libary("rjd3x13")
libary("rjd3workspace")
libary("rjd3tramoseats")
libary("rjd3sts")
libary("rjd3filters")
libary("rjd3highfreq")
libary("rjd3stl")
libary("rjd3x11plus")
